### ISSUE TITLE
Debugging toIBuffer

### ISSUE THREAD

**Issue by logidelic** [NodeRT/nodert-streams#2]
I'm using nodert-streams and things seem to work. However, I'm running into a crash that occurs sporadically. I've isolated a bit and am wondering if toIBuffer() might be implicated. Here is the offending code:

```
var InMemoryRandomAccessStream  = require('@nodert-win10/windows.storage.streams').InMemoryRandomAccessStream;
var nodertStreams = require('@nodert-win10/nodert-streams');

var strm = new InMemoryRandomAccessStream();
var buf  = new Buffer(imageBuf); // imageBuf is Uint8Array of length ~80,000
var ibuf = nodertStreams.toIBuffer(buf);
console.log('We get here fine');
strm.writeAsync(ibuf, function(err) {
    console.log('We\'ve already crashed (sometimes!));
});
```

As you can see, I'm taking an ~80k node `Buffer` and converting it to an `IBuffer` using `toIBuffer()`. Finally, I'm writing said buffer to an `InMemoryRandomAccessStream`. the call to `writeAsync()` crashes my application, _sometimes_.

Is there a way to validate the IBuffer? Is it possible that it is somehow corrupted?

I have this code executed repeatedly, (with different imageBuf input), many times per second. It works perfectly for several iterations until it finally crashes on the call to `writeAsync()`. Am I right in suspecting `toIBuffer()`? Any suggestions on how to debug?

Thanks.

**Comment by logidelic** [comment]
A bit more info: I caught this under the debugger and found the following:

The crash is happening on the actual call to `WriteAsync()` from within the NodeRT wrapper:

```
    static void WriteAsync(Nan::NAN_METHOD_ARGS_TYPE info)
    {
      ...
        try
        {
          ::Windows::Storage::Streams::IBuffer^ arg0 = UnwrapIBuffer(info[0]);
          
          op = wrapper->_instance->WriteAsync(arg0); // Crash here!
```

The error I get in the debugger is:

> Exception thrown at 0x00007FFEBF7836DA (msvcrt.dll) in App.exe: 0xC0000005: Access violation reading location 0x0000022B890BF126.

Finally, I notice that `arg0` above has its `m_length` set **correctly**, however, its `m_buffer` member shows _"error reading characters of string"_. If I break on a non-crash iteration, I see some (binary) characters displayed for `m_buffer`. Seems to suggest a corrupted IBuffer?

**Comment by logidelic** [comment]
One more bit of info:

Run under different circumstances, the IBuffer-based stream is corrupted, but the app doesn't crash. In these cases, I was able to do byte-by-byte comparison of the two.

What I found is that on every occasion, of the ~80k bytes, **only the first 16 bytes were corrupted**! Hopefully this is a clue.

**Comment by nadavbar** [comment]
Hi @logidelic, thanks for the deep investigation :)
I have a suspicion that the issue happens due to the node.js buffer being cleaned by the GC. Can you run the following simple test:
Before running the code, use an external variable (or even global) to hold the node.js buffer. 
Can you test and see if maybe this olves the issue?
If this is indeed the case then the fix in nodert-streams should be pretty simple.

**Comment by logidelic** [comment]
Thanks for the suggestion @nadavbar . Unfortunately I had the same thought and tried that. Doesn't seem to change anything. :(

Here's another test that exposes the issue:

```
window.strm = new InMemoryRandomAccessStream();
window.buf  = new Buffer(imageBuf);
window.ibuf = nodertStreams.toIBuffer(window.buf);

var reader = DataReader.fromBuffer(window.ibuf);

var bufBytes = [];
var ibufBytes = [];
var same = true;
for(var i = 0; i < 16; ++i) {
    var bufByte  = parseInt(window.buf[i]);
    var ibufByte = parseInt(reader.readByte());
    same = same && (bufByte == ibufByte);
    bufBytes.push(bufByte);
    ibufBytes.push(ibufByte);
}
if(!same)
    console.log(JSON.stringify(bufBytes) + ' vs ' + JSON.stringify(ibufBytes));
```

As per my original post, this works correctly for the great majority of iterations (i.e. the bytes are the same). However, in the problem passes, I get output such as:

> [255,216,255,224,0,16,74,70,73,70,0,1,1,0,0,1] vs [255,216,255,224,220,1,0,0,64,213,103,132,220,1,0,0]


What I'm trying to wrap my head around: In the documentation you state that `toIBuffer `makes use of the the same underlying data buffer. If so, how can it be possible that the first few bytes get corrupted, and the rest of the bytes are ok, while the original node `Buffer `remains untouched?

**Comment by logidelic** [comment]
One more thing that I should mention is that I'm using this in an electron renderer process where I've `require`d nodert-streams via `remote`. Perhaps this is relevant; I'm not sure.

**Comment by nadavbar** [comment]
I've pushed a potential fix which adds a call to scope.Escape before the buffer is returned back to JavaScript-land, and another change that makes sure that the node.js buffer stays in memory as long as the IBuffer stays in memory. Can you try and see if this fixes the issue? (This fix was also pushed to the module which is available in npm)
It's possible that not having that call caused the buffer to be released ahead of time.

**Comment by logidelic** [comment]
I believe this fixed it! Thanks!
